---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  # Protect secrets using Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
  # Supported base hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [-c, .github/linters/.markdownlint.yml]
        types: [file]
        files: .(md|qmd)$
  # Add trailing commas to calls and literals.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
      - id: add-trailing-comma
  # Opinionated code styling
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  # PEP 8 style guide, error and complexity checks
  # Replaces Flake8, isort, pydocstyle, pyupgrade, bandit, and autoflake
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff
        args: [--config=./.github/linters/ruff.toml]
